### ISSUE TITLE
port to systemd

### ISSUE THREAD

**Issue by bmaeser** [bmaeser/iptables-boilerplate#11]
title says it all

**Comment by SudoAsk** [comment]
So interesting  :)

**Comment by gagomap** [comment]
@bmaeser : Can you support fail2ban service start at boot after iptables-boilerplate as a default setting ? Because fail2ban will not runs normally (service doesn't run) if it starts before iptables-boilerplate does. 

In the version 1, i added these line to firewall:

`echo "firewall started"
	    echo "restarting fail2ban"
	    /etc/init.d/fail2ban restart
        ;;

    stop)
	    echo "stopping fail2ban"
	    /etc/init.d/fail2ban stop
 echo "stopping firewall..."`

Thank you :D

**Comment by bmaeser** [comment]
@gagomap please open new issues with proper title

and: if you start fail2ban prior to iptables-boilerplate, the firewall will overwrite all rules set by fail2ban
thats what the custom-scripts folder is for. if you start fail2ban via script in there, everything works as expected.
